# Project 3

NYC is famous for it's parks, and lack of public toilet. Imagine you are on your morning run (or walk) and a sudden urge for toilet arises? chances are, you'll go to the nearest cafe, order the cheapest menu and ask for the toilet code. So, here's an analysis of Parks in NYC and pubic park toilet of each Borough. Hang on, you got this!
let's deep dive on this

# Step 1 -Importing the data

We will inspect [NYC Park Data]("https://data.cityofnewyork.us/Recreation/Parks-Properties/enfh-gkve/about_data") and [NYC Public Toilet (at Park) Directorty]("https://data.cityofnewyork.us/Recreation/Directory-Of-Toilets-In-Public-Parks/hjae-yuav/about_data"), mind you, there are a lot to hande

In [1]:
# import necessary packages

import pandas as pd
import plotly.express as px

# import NYC park data

park = pd.read_csv("Parks_Properties_20251205.csv", delimiter=",")

park

,ACQUISITIONDATE,ACRES,ADDRESS,BOROUGH,CLASS,COMMUNITYBOARD,COUNCILDISTRICT,DEPARTMENT,EAPPLY,GISOBJID,...,PIP_RATABLE,PRECINCT,RETIRED,SIGNNAME,SUBCATEGORY,TYPECATEGORY,US_CONGRESS,WATERFRONT,ZIPCODE,multipolygon
0,1972 Sep 22 12:00:00 AM,83.3,1000 RICHMOND TERRACE,R,PARK,501,49,R-01,Snug Harbor Cultural Center,"100,003,741",...,False,120,False,Snug Harbor Cultural Center,Large Park,Historic House Park,11,True,"10301, 10310",MULTIPOLYGON (((-74.10086903940999 40.64468646...
1,NaN,0.356,200-15 MCLAUGHLIN AV,Q,PARK,408,23,Q-08,McLaughlin Playground,"100,000,044",...,True,107,False,McLaughlin Playground,Neighborhood Plgd,Playground,5,False,11423,MULTIPOLYGON (((-73.76596231448613 40.72551186...
2,1926 Apr 29 12:00:00 AM,286.557,298 SATERLEE STREET,R,PARK,503,51,R-03,Conference House Park,"100,004,319",...,False,123,False,Conference House Park,Large Park,Nature Area,11,True,"10307, 10309",MULTIPOLYGON (((-74.25204073763335 40.50292259...
3,1990 Oct 26 12:00:00 AM,6.611,2 KENT STREET,B,PARK,301,33,B-01,WNYC Transmitter Park,"100,003,886",...,True,94,False,WNYC Transmitter Park,Neighborhood Park,Neighborhood Park,NaN,True,11222,MULTIPOLYGON (((-73.96140516032709 40.73032004...
4,1948 Jan 29 12:00:00 AM,1.534,255 PARKINSON AVENUE,R,PARK,502,50,R-02B,Old Town Playground,"100,004,659",...,True,122,False,Old Town Playground,JOP,Playground,11,False,10305,MULTIPOLYGON (((-74.08082911468377 40.59514394...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2050,NaN,8.595,NaN,M,PARK,"108,111","5, 8",M-15,East River Esplanade 90th-125th,"100,004,777",...,False,19,False,East River Esplanade,Sitting Area/Triangle/Mall,Waterfront Facility,"1,213",True,"10028, 10029, 10035, 10128",MULTIPOLYGON (((-73.94261918171239 40.78379646...
2051,2024 Dec 20 12:00:00 AM,0.172,NaN,B,PARK,306,39,B-06,Park,"100,046,330",...,False,76,False,Park,NaN,Undeveloped,10,True,11231,MULTIPOLYGON (((-73.99641750174982 40.67438152...
2052,NaN,0.004,NaN,B,PARK,302,35,B-02,NaN,NaN,...,False,88,False,Fowler Square,NaN,Triangle/Plaza,10,False,11217,MULTIPOLYGON (((-73.97567939206937 40.68697572...
2053,1835 Apr 08 12:00:00 AM,254.3,NaN,M,PARK,111,8,M-11R,Randall's Island Park,"100,004,488",...,False,25,False,Randall's Island Park,Flagship Park,Flagship Park,13,True,10035,MULTIPOLYGON (((-73.92594504670001 40.79086407...
2054,1980 Oct 01 12:00:00 AM,44.295,NaN,Q,PARK,411,19,Q-07A,Udall's Park Preserve,"100,000,036",...,True,111,False,Udall's Park Preserve,Large Park,Nature Area,3,True,11363,MULTIPOLYGON (((-73.74645122415272 40.78014090...

In [2]:
# import NYC Park toilet data

toilet = pd.read_csv("Directory_Of_Toilets_In_Public_Parks_20251205.csv", delimiter=",")

toilet

,Name,Location,Open Year-Round,Handicap Accessible,Borough,Comments
0,100% Playground,"Glenwood Road, East 100 & East 101 streets",Yes,NaN,Brooklyn,NaN
1,174th Street Playground,"East 174 Street, Stratford Avenue, Bronx River...",Yes,NaN,Bronx,NaN
2,227 Street Playground,Bronx Boulevard between East 226 and East 228 ...,Yes,Yes,Bronx,NaN
3,Abe Lincoln,"East 135 Street, between Madison & 5 avenues",Yes,NaN,Manhattan,NaN
4,Abigail Playground,"East 156 Street, Tinton Avenue",No,NaN,Bronx,NaN
...,...,...,...,...,...,...
611,Wingate Park,Brooklyn Avenue & Rutland Road,Yes,NaN,Brooklyn,NaN
612,Woods Playground,Bergen Street & Utica Avenue,Yes,NaN,Brooklyn,NaN
613,Woodtree Playground,"20 Avenue, 37 Street, 38 Street",Yes,NaN,Queens,NaN
614,Yak Playground,Avenue Y between Coyle & Batchelder streets,Yes,Yes,Brooklyn,NaN
615,Zimmerman Playground,"Britton Street, Barker Avenue, Olinville Avenue",No,NaN,Bronx,NaN

# Analysis question
- How many outdoor recereation(on this case, park) each Borouggh in NYC and how it correlates with the number of public toilet in park in eaach Borough in NYC?

# Step 2a - Data Cleaning and Formatting - Park Dataset
we need to do some data handling to ensure that each data set has the same format

Columns that are likely to be used in park dataset, and how we handle them:
- Borough : Change the code in "Borough" series according to [this data dictionary]("https://docs.google.com/spreadsheets/d/1Q4DBWu7riNFxWvy1vnTJHoOI3r2L9oW6eCN56jCNyCw/edit?gid=0#gid=0"")
- TYPECATEGORY = The type of property according to Planning and Development Division of the New York City Department of Parks and Recreation. [see]("https://docs.google.com/document/d/1NExNJF5YKID04oOopi0fHainRuGG3Pz_jKSrMujPsPk/edit?tab=t.0")
- Acres = Size of the park property (in acres).

In [3]:
# check null value in borough
park["BOROUGH"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2055 entries, 0 to 2054
Series name: BOROUGH
Non-Null Count  Dtype
--------------  -----
2055 non-null   object
dtypes: object(1)
memory usage: 16.2+ KB

In [4]:
# check unique data in Borough
park["BOROUGH"].unique()

array(['R', 'Q', 'B', 'X', 'M'], dtype=object)

In [5]:
BORO = []

for code in park["BOROUGH"]:
    if code == "B":
        BORO.append("Brooklyn")
    elif code == "M":
        BORO.append("Manhattan")
    elif code == "Q":
        BORO.append("Queens")
    elif code == "R":
        BORO.append("Staten Island")
    elif code == "X":
        BORO.append("Bronx")
    else:
        BORO.append("Unknown")

# add the list to data frame
park["BORO"] = BORO
# check the result
print(park["BOROUGH"].unique())
print(park["BORO"].unique())
park

['R' 'Q' 'B' 'X' 'M']
['Staten Island' 'Queens' 'Brooklyn' 'Bronx' 'Manhattan']

,ACQUISITIONDATE,ACRES,ADDRESS,BOROUGH,CLASS,COMMUNITYBOARD,COUNCILDISTRICT,DEPARTMENT,EAPPLY,GISOBJID,...,PRECINCT,RETIRED,SIGNNAME,SUBCATEGORY,TYPECATEGORY,US_CONGRESS,WATERFRONT,ZIPCODE,multipolygon,BORO
0,1972 Sep 22 12:00:00 AM,83.3,1000 RICHMOND TERRACE,R,PARK,501,49,R-01,Snug Harbor Cultural Center,"100,003,741",...,120,False,Snug Harbor Cultural Center,Large Park,Historic House Park,11,True,"10301, 10310",MULTIPOLYGON (((-74.10086903940999 40.64468646...,Staten Island
1,NaN,0.356,200-15 MCLAUGHLIN AV,Q,PARK,408,23,Q-08,McLaughlin Playground,"100,000,044",...,107,False,McLaughlin Playground,Neighborhood Plgd,Playground,5,False,11423,MULTIPOLYGON (((-73.76596231448613 40.72551186...,Queens
2,1926 Apr 29 12:00:00 AM,286.557,298 SATERLEE STREET,R,PARK,503,51,R-03,Conference House Park,"100,004,319",...,123,False,Conference House Park,Large Park,Nature Area,11,True,"10307, 10309",MULTIPOLYGON (((-74.25204073763335 40.50292259...,Staten Island
3,1990 Oct 26 12:00:00 AM,6.611,2 KENT STREET,B,PARK,301,33,B-01,WNYC Transmitter Park,"100,003,886",...,94,False,WNYC Transmitter Park,Neighborhood Park,Neighborhood Park,NaN,True,11222,MULTIPOLYGON (((-73.96140516032709 40.73032004...,Brooklyn
4,1948 Jan 29 12:00:00 AM,1.534,255 PARKINSON AVENUE,R,PARK,502,50,R-02B,Old Town Playground,"100,004,659",...,122,False,Old Town Playground,JOP,Playground,11,False,10305,MULTIPOLYGON (((-74.08082911468377 40.59514394...,Staten Island
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2050,NaN,8.595,NaN,M,PARK,"108,111","5, 8",M-15,East River Esplanade 90th-125th,"100,004,777",...,19,False,East River Esplanade,Sitting Area/Triangle/Mall,Waterfront Facility,"1,213",True,"10028, 10029, 10035, 10128",MULTIPOLYGON (((-73.94261918171239 40.78379646...,Manhattan
2051,2024 Dec 20 12:00:00 AM,0.172,NaN,B,PARK,306,39,B-06,Park,"100,046,330",...,76,False,Park,NaN,Undeveloped,10,True,11231,MULTIPOLYGON (((-73.99641750174982 40.67438152...,Brooklyn
2052,NaN,0.004,NaN,B,PARK,302,35,B-02,NaN,NaN,...,88,False,Fowler Square,NaN,Triangle/Plaza,10,False,11217,MULTIPOLYGON (((-73.97567939206937 40.68697572...,Brooklyn
2053,1835 Apr 08 12:00:00 AM,254.3,NaN,M,PARK,111,8,M-11R,Randall's Island Park,"100,004,488",...,25,False,Randall's Island Park,Flagship Park,Flagship Park,13,True,10035,MULTIPOLYGON (((-73.92594504670001 40.79086407...,Manhattan
2054,1980 Oct 01 12:00:00 AM,44.295,NaN,Q,PARK,411,19,Q-07A,Udall's Park Preserve,"100,000,036",...,111,False,Udall's Park Preserve,Large Park,Nature Area,3,True,11363,MULTIPOLYGON (((-73.74645122415272 40.78014090...,Queens

In [6]:
# Handling Area Data

park["ACRES"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2055 entries, 0 to 2054
Series name: ACRES
Non-Null Count  Dtype
--------------  -----
2055 non-null   object
dtypes: object(1)
memory usage: 16.2+ KB

The acres column is in string, so we need to convert it to float

In [7]:
# change acre data type to folat, and omit comas
park["ACRES"] = park["ACRES"].str.replace(",", "").astype(float)

park["ACRES"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 2055 entries, 0 to 2054
Series name: ACRES
Non-Null Count  Dtype
--------------  -----
2055 non-null   float64
dtypes: float64(1)
memory usage: 16.2 KB

let's check the Rercreational Spot type

In [13]:
# check TYPECATEGORY series info
park["TYPECATEGORY"].info()

# check TYPECATEGORY unique values
park["TYPECATEGORY"].unique()

<class 'pandas.core.series.Series'>
RangeIndex: 2055 entries, 0 to 2054
Series name: TYPECATEGORY
Non-Null Count  Dtype
--------------  -----
2055 non-null   object
dtypes: object(1)
memory usage: 16.2+ KB

array(['Historic House Park', 'Playground', 'Nature Area',
       'Neighborhood Park', 'Triangle/Plaza', 'Garden',
       'Jointly Operated Playground', 'Recreational Field/Courts',
       'Community Park', 'Undeveloped', 'Cemetery', 'Parkway',
       'Buildings/Institutions', 'Strip', 'Managed Sites', 'Lot',
       'Flagship Park', 'Waterfront Facility', 'Mall', 'Operations',
       'Retired N/A'], dtype=object)

we need to filter the park data to only take park category that is possible for recreation, mainly (but not all) managed by NYCPARKS. (I'm open to every suggestion to add or omit some categories)

In [22]:
# set the valid Categories
valid_categories = [
    "Community Park",
    "Neighborhood Park",
    "Playground",
    "Flagship Park",
    "Jointly Operated Playground",
    "Recreational Field/Courts",
    "Triangle/Plaza",
    "Waterfront Facility",
    "Nature Area",
]

# filter TYPE CATEGORY by valid category
park_filtered = park[park["TYPECATEGORY"].isin(valid_categories)]

park_filtered

,ACQUISITIONDATE,ACRES,ADDRESS,BOROUGH,CLASS,COMMUNITYBOARD,COUNCILDISTRICT,DEPARTMENT,EAPPLY,GISOBJID,...,PRECINCT,RETIRED,SIGNNAME,SUBCATEGORY,TYPECATEGORY,US_CONGRESS,WATERFRONT,ZIPCODE,multipolygon,BORO
1,NaN,0.356,200-15 MCLAUGHLIN AV,Q,PARK,408,23,Q-08,McLaughlin Playground,"100,000,044",...,107,False,McLaughlin Playground,Neighborhood Plgd,Playground,5,False,11423,MULTIPOLYGON (((-73.76596231448613 40.72551186...,Queens
2,1926 Apr 29 12:00:00 AM,286.557,298 SATERLEE STREET,R,PARK,503,51,R-03,Conference House Park,"100,004,319",...,123,False,Conference House Park,Large Park,Nature Area,11,True,"10307, 10309",MULTIPOLYGON (((-74.25204073763335 40.50292259...,Staten Island
3,1990 Oct 26 12:00:00 AM,6.611,2 KENT STREET,B,PARK,301,33,B-01,WNYC Transmitter Park,"100,003,886",...,94,False,WNYC Transmitter Park,Neighborhood Park,Neighborhood Park,NaN,True,11222,MULTIPOLYGON (((-73.96140516032709 40.73032004...,Brooklyn
4,1948 Jan 29 12:00:00 AM,1.534,255 PARKINSON AVENUE,R,PARK,502,50,R-02B,Old Town Playground,"100,004,659",...,122,False,Old Town Playground,JOP,Playground,11,False,10305,MULTIPOLYGON (((-74.08082911468377 40.59514394...,Staten Island
5,1973 Dec 30 12:00:00 AM,0.670,750-802 RIVER AV,X,PARK,204,16,X-04,River Avenue Parks,"100,004,862",...,44,False,River Avenue Parks,Neighborhood Plgd,Playground,15,False,10451,MULTIPOLYGON (((-73.92706900971802 40.82485894...,Bronx
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2049,1943 Apr 02 12:00:00 AM,5.593,114-30 NORTH CONDUIT AVENUE,Q,PARK,410,28,Q-10,Southern Fields,"100,007,898",...,106,False,Southern Fields,Neighborhood Park,Recreational Field/Courts,5,False,11420,MULTIPOLYGON (((-73.82491051650112 40.66599969...,Queens
2050,NaN,8.595,NaN,M,PARK,"108,111","5, 8",M-15,East River Esplanade 90th-125th,"100,004,777",...,19,False,East River Esplanade,Sitting Area/Triangle/Mall,Waterfront Facility,"1,213",True,"10028, 10029, 10035, 10128",MULTIPOLYGON (((-73.94261918171239 40.78379646...,Manhattan
2052,NaN,0.004,NaN,B,PARK,302,35,B-02,NaN,NaN,...,88,False,Fowler Square,NaN,Triangle/Plaza,10,False,11217,MULTIPOLYGON (((-73.97567939206937 40.68697572...,Brooklyn
2053,1835 Apr 08 12:00:00 AM,254.300,NaN,M,PARK,111,8,M-11R,Randall's Island Park,"100,004,488",...,25,False,Randall's Island Park,Flagship Park,Flagship Park,13,True,10035,MULTIPOLYGON (((-73.92594504670001 40.79086407...,Manhattan
2054,1980 Oct 01 12:00:00 AM,44.295,NaN,Q,PARK,411,19,Q-07A,Udall's Park Preserve,"100,000,036",...,111,False,Udall's Park Preserve,Large Park,Nature Area,3,True,11363,MULTIPOLYGON (((-73.74645122415272 40.78014090...,Queens

all datas in park dataset are classified as park

# Step 2b - Data Cleaning and Formatting - Toilet Dataset
working on toilet data set

In [10]:
# check toilet data frame info
toilet.info()

# check unique values and info of Borough colums
toilet["Borough"].info()

toilet["Borough"].unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 616 entries, 0 to 615
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Name                 616 non-null    object
 1   Location             615 non-null    object
 2   Open Year-Round      589 non-null    object
 3   Handicap Accessible  129 non-null    object
 4   Borough              616 non-null    object
 5   Comments             8 non-null      object
dtypes: object(6)
memory usage: 29.0+ KB
<class 'pandas.core.series.Series'>
RangeIndex: 616 entries, 0 to 615
Series name: Borough
Non-Null Count  Dtype
--------------  -----
616 non-null    object
dtypes: object(1)
memory usage: 4.9+ KB

array(['Brooklyn', 'Bronx', 'Manhattan', 'Queens', 'Staten Island'],
      dtype=object)

there are no nulls value in Borough Dataset and no transformation needed. fyuh.

# Hypothesis 
Some NYC boroughs (Brooklyn, Queens, and Staten Island) have significantly fewer public toilets relative to the number of parks they contain. 
This may indicate unequal access to essential sanitation infrastructure, suggesting the need for targeted policy interventions in underserved boroughs.

1. Number of Parks Per Borough

In [23]:
# calculate number of park per borough
park_count = park_filtered.groupby("BORO").size().reset_index(name="TOTAL_PARK")

park_count

            BORO  TOTAL_PARK
0          Bronx         275
1       Brooklyn         416
2      Manhattan         262
3         Queens         385
4  Staten Island         134